return {
    id = 'tree sync publisher',
    title = LOC "$$$/rcTreeSyncPublisher/Tagset/Title=Tree Sync Tagset from Plug-in",
    schemaVersion = 1,
    items = {
        'com.adobe.filename',
        'com.adobe.copyname',
        'com.adobe.folder',
        'com.adobe.separator',
        'com.adobe.title',
        'com.adobe.colorLabels',
        'com.adobe.rating',
        'com.adobe.keywords',
        -- 'com.adobe.metadata',
        -- 'com.adobe.exif',
        'com.adobe.captureTime',
        -- 'com.adobe.camera',
        -- 'com.adobe.cameraSN',
        { 'com.adobe.caption', height_in_lines = 3 },
        'com.adobe.separator',
        { 'com.adobe.label', label = LOC "$$$/Metadata/CusLabel=My Metadata list" },
        'com.robcole.lightroom.TreeSyncPublisher.*',
        'com.adobe.separator',
        { 'com.adobe.label', label = LOC "$$$/Metadata/SampleLabel=Section Label" },
        'com.adobe.dateCreated',
        'com.adobe.city',
        'com.adobe.state',
        'com.adobe.country',
        'com.adobe.isoCountryCode',
        'com.adobe.lightroom.metadata.sample.randomString',
        'com.adobe.altTextAccessibility',
        'com.adobe.extDescrAccessibility',
    },
}